### ISSUE TITLE
View Connectome with nilearn

### ISSUE THREAD

**Issue by wingedRuslan** [WhitakerLab/scona#144]
Hi there,

while creating a function to view connectome with nilearn (3d - interactively), I realized that we can not make pretty plots as long as all edge weights of thresholded graph = 1. 

![image](https://user-images.githubusercontent.com/14000852/61748617-6067bb80-ada9-11e9-9eea-5ebd645f5889.png)

Even if we plot a threshold graph at cost 2 (G02), we get quite "messy" Graph, because of so many connections.

[Nilearn](http://nilearn.github.io/modules/generated/nilearn.plotting.view_connectome.html#nilearn.plotting.view_connectome) has a property to handle the number of plotted edges - **edge_threshold**, but it can only be applied if edges have different weights.

>    edge_threshold : str, number or None, optional (default=None)
        If None, no thresholding.
        If it is a number only connections of amplitude greater
        than threshold will be shown.
        If it is a string it must finish with a percent sign,
        e.g. "25.3%", and only connections of amplitude above the
        given percentile will be shown.

In out case all edges have weights = 1.

Right now I do not know how to reduce the number of plotted edges...

**Comment by Islast** [comment]
This is a big find! I'm sorry I was in the meeting yesterday to discuss it with you. 
We could create a copy of the graph and take threshold of the `edge_weight` attribute in that and then dispose of it when the plotting is done. This is clunky for sure, but since we usually only decide to plot one or two networks in this way, hopefully wouldn't be cripplingly time consuming.

The alternative is to take the nilearn method apart and rewrite it in such a way that accepts a different way of specifying which edges exist. Having taken a look at these methods myself, this looks like quite a challenge. perhaps we should communicate more with nilearn. I'm sure they would be interested to hear about the problems we're having

**Comment by KirstieJane** [comment]
Sorry for not keeping this up to date @Islast.

I recommended that @wingedRuslan just pass the original graph (`G`) before it is thresholded for the plotting. Should work fine I think!

**Comment by Islast** [comment]
Smart!

**Comment by KirstieJane** [comment]
I think we can close this, right? Addressed in #145

**Comment by wingedRuslan** [comment]
@KirstieJane, yeah, that's right! 

Closing the issue, addressed in #145
